stages:
  setup:
    cmd: python -m src.setup
    deps:
      - src/setup.py
      - paths.py
      - data/raw/supermarket.db
    outs:
      - data/transformed/work.parquet
      - data/validation/validation.parquet

  preprocess:
    cmd: python -m src.preprocessing
    deps:
      - src/preprocessing.py
      - data/transformed/work.parquet
    outs:
      - data/transformed/work_result_quality.parquet
      - data/transformed/num_result_quality.parquet
      - data/transformed/cat_result_quality.parquet

  feature_engineering:
    cmd: python -m src.feature_engineering
    deps:
      - src/feature_engineering.py
      - data/transformed/num_result_quality.parquet
      - data/transformed/cat_result_quality.parquet
    outs:
      - data/transformed/df_transformed.parquet
